app: annict
name: work
component: aws-dynamodb
stage: dev

inputs:
  name: ${stage}-${app}-${name}
  deletionPolicy: delete # allows table to be removed. This property is a safe guard.
  attributeDefinitions:
    - AttributeName: id
      AttributeType: N
    - AttributeName: release_year
      AttributeType: N
    - AttributeName: release_cours
      AttributeType: S
  keySchema:
    - AttributeName: id
      KeyType: HASH
  globalSecondaryIndexes:
    - IndexName: 'ReleaseYear-ReleaseCours-Index'
      KeySchema:
        - AttributeName: release_year
          KeyType: HASH
        - AttributeName: release_cours
          KeyType: RANGE
      Projection:
        ProjectionType: 'ALL'
  region: ap-northeast-1
  BillingMode: PAY_PER_REQUEST
  # ProvisionedThroughput:
  #   ReadCapacityUnits: 5
  #   WriteCapacityUnits: 5
